services:
  backend:
    build:
      context: ./backend
    container_name: splitwise-backend
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/splitwise
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: splitwise-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: splitwise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  frontend:
    build:
      context: ./frontend/splitwise-ui
    container_name: splitwise-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
